#@ load("@ytt:data", "data")

#@ load("commons.lib.yml", 
#@   "testflight_group_name",
#@   "testflight_bootstrap_job_name",
#@   "testflight_inception_job_name",
#@   "testflight_platform_job_name",
#@   "testflight_services_job_name",
#@   "testflight_cleanup_job_name",
#@   "bump_repos_job_name",
#@   "build_pipeline_image_job_name",
#@   "common_resources",
#@   "resource_types")

#@ load("gcp.lib.yml",
#@   "gcp_jobs",
#@   "gcp_resources")

#@ supported_iaas = ["gcp", "azure"]
groups:
#@ for cloud in supported_iaas:
- name: #@ testflight_group_name(cloud)
  jobs:
  - #@ testflight_bootstrap_job_name(cloud)
  - #@ testflight_inception_job_name(cloud)
  - #@ testflight_platform_job_name(cloud)
  - #@ testflight_services_job_name(cloud)
  - #@ testflight_cleanup_job_name(cloud)
  - #@ bump_repos_job_name(cloud)
#@ end
- name: image
  jobs:
#@ for cloud in supported_iaas:
  - #@ build_pipeline_image_job_name(cloud)
#@ end
- name: k8s-upgrade
  jobs:
  - check-and-upgrade-k8s

jobs:
#@ for/end job in gcp_jobs():
- #@ job

- name: check-and-upgrade-k8s
  plan:
  - in_parallel:
    - get: daily-trigger-resource
      trigger: true
    - get: repo
    - get: pipeline-tasks
  - task: check-and-upgrade-k8s
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          username: #@ data.values.docker_registry_user
          password: #@ data.values.docker_registry_password
          repository: #@ data.values.docker_registry + "/galoy-deployments-pipeline"
      inputs:
      - name: repo
      - name: pipeline-tasks
      outputs:
      - name: repo
      params:
        BRANCH: #@ data.values.git_branch
      run:
        path: pipeline-tasks/ci/tasks/check-and-upgrade-k8s.sh
  - put: repo
    params:
      repository: repo
      rebase: true

resources:
#@ for/end resource in common_resources():
- #@ resource

#@ for/end resource in gcp_resources():
- #@ resource

- name: daily-trigger-resource
  type: time
  source:
    start: 1:00 AM
    stop: 2:00 AM

resource_types: #@ resource_types()
