#!/bin/bash

set -e

if [[ $(which ytt) == "" ]]; then
  echo "You will need to install ytt to repipe. https://carvel.dev/ytt/"
  exit 1
fi

target="${FLY_TARGET:-ciblink}"
team=dev

BUILDDIR="ci/build"
mkdir -p $BUILDDIR

ytt -f ci > ${BUILDDIR}/pipeline.yml

echo "Updating pipeline @ ${target}"

fly -t ${target} set-pipeline --team=${team} -p blink-infra -c ${BUILDDIR}/pipeline.yml
fly -t ${target} unpause-pipeline --team=${team} -p blink-infra
