name: Check formatting
on:
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Tofu fmt
        uses: opentofu/setup-opentofu@v1
      - run: tofu fmt -recursive .
      - run: git diff --exit-code
